---
swagger: "2.0"
info:
  description: "Image Processing API"
  version: "1.0.0"
  title: "Image Processor"
host: "localhost:8080"
basePath: "/image"
schemes:
- "https"
paths:
  /process:
n    post:
      summary: Takes an image and processes it according to accompanying json
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: image
        type: file
        description: The image
        required: true
      - in: formData
        name: processes
        type: file
        description: JSON string containing array of the processes, in the order they should be preformed 
        required: true
      responses:
        200:
          description: OK

definitions:
  Processes:
    type: "object"
    required:
    - "list_of_Process"
    properties:
      list_of_Process:
        type: "array"
        items:
          $ref: "#/definitions/Process"
  Process:
    type: object
    properties:
      type:
        type: string
        enum: 
        - rotate
        - scale
        - crop
        - mirror
        - color
        - brightness
        - contrast
        - sharpen
        - blur
        - maxFilter
        - minFilter
        - medianFilter
        - edge
      list_of_Parameter:
        type: array
        items:
          $ref: "#/definitions/Parameter"
    discriminator: type
    required:
      - type
  Parameter:
    type: object
    properties:
      parameter:
        type: string
      value:
        type: string
    required:
    - parameter
    - value
  Process --> Rotate:
    description: Rotate image N degrees
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "list_of_Parameter"
        properties:
          type:
            enum: 
            - Rotate
          list_of_Parameter:
            description: 1 item list containing the degrees to rotate the image
            items:
              type: object
              properties:
                parameter:
                  description: Number of degrees to rotate
                  type: string
                  enum: 
                  - degrees
                value:
                 type: string
                 description: Converted to type float.
  Process --> Scale:
    description: Scale an image along the x-axis, y-axis, or both.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "list_of_Parameter"
        properties:
          type:
            enum: 
            - Scale
          list_of_Parameter:
            description: xsize, ysize, or both
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum: 
                  - xsize
                  - ysize
                  description: Specify an x size, y size, or both.
                value:
                 type: string
                 description: Converted to type int.
                 

                

    
          
