---
swagger: "2.0"
info:
  description: "Image Processing API"
  version: "1.0.0"
  title: "Image Processor"
host: "localhost:5000"
basePath: "/image"
schemes:
- "http"
paths:
  /image-process:
    post:
      summary: Supports all operations.
      description: Consumes a form with the image to be processed, and an accompanying json that specifies the processes to preform.
      consumes:
      - multipart/form-data
      parameters:
      - in: formData
        name: Image
        type: file
        description: The image.
        required: true
      - in: formData
        name: Processes
        type: file
        description: JSON object containing array of Process, in the order they should be preformed. 
        required: true
      responses:
        200:
          description: OK

definitions:
  Processes:
    description: Object containing the array of processes to preform on the image. Processes will be carried out in the order listed.
    type: "object"
    required:
    - "processes"
    properties:
      format:
        type: object
        properties:
          type: 
            description: "The type of format to return"
            type: string
            enum:
              - JPEG
              - PNG
              - GIF
              - TIFF
              - BMP
              - EPS
              - ICO
              - TGA              
          quality:
            description: "The quality setting to return - only used for jpeg"
            type: number 
      processes:
        type: "array"
        items:
          $ref: "#/definitions/Process"
        example:
          - name: Rotate
            parameters:
              - parameter: degrees
                value: "30"
          - name: Scale
            parameters:
              - parameter: xsize
                value: "30"
          - name: Crop
            parameters:
              - parameter: top_left_x
                value: "30"
              - parameter: top_left_y
                value: "30"
              - parameter: bottom_right_x
                value: "60"
              - parameter: bottom_right_y
                value: "60"
          - name: Mirror
            parameters:
              - parameter: flip
                value: "horizontal"
          - name: Color
            parameters:
              - parameter: factor
                value: "1.7"
          - name: Brightness
            parameters:
              - parameter: factor
                value: "1.7"
          - name: Contrast
            parameters:
              - parameter: factor
                value: "1.7"
          - name: Sharpen
            parameters:
              - parameter: factor
                value: "1.7"
          - name: Blur
            parameters:
              - parameter: radius
                value: "1.7"
          - name: MaxFilter
            parameters:
              - parameter: size
                value: "3"
          - name: MinFilter
            parameters:
              - parameter: size
                value: "3"
          - name: ModeFilter
            parameters:
              - parameter: size
                value: "3"
          - name: MedianFilter
            parameters:
              - parameter: size
                value: "3"
          - name: Edge
            parameters:

  Process:
    description: Specification of a single process.
    type: object
    properties:
      name:
        description: The name of image processing you want to preform. See Enum for array of supported processes.
        type: string
        example: Rotate
        enum: 
        - Rotate
        - Scale
        - Crop
        - Mirror
        - Color
        - Brightness
        - Contrast
        - Sharpen
        - Blur
        - MaxFilter
        - MinFilter
        - ModeFilter
        - MedianFilter
        - Edge
      parameters:
        description: Parameter array to further specify the process, if necessary.
        type: array
        items:
          $ref: "#/definitions/Parameter"
        example:
          - parameter: degrees
            value: "30"
    discriminator: name
    required:
      - name

  Parameter:
    description: General definition for a Parameter. See extended Process definitions below for 
    type: object
    properties:
      parameter:
        type: string
        example: degrees
      value:
        type: string
        example: "30"
    required:
    - parameter
    - value

  Process --> Rotate:
    description: Rotate image N degrees.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Rotate
          parameters:
            description: Single item array containing the degrees to rotate the image.
            items:
              type: object
              properties:
                parameter:
                  description: Number of degrees to rotate.
                  type: string
                  enum: 
                  - degrees
                value:
                 type: string
                 description: Converted to type float.

  Process --> Scale:
    description: Scale an image along the x-axis, y-axis, or both.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Scale
            example: Scale
          parameters:
            description: Provide xsize, ysize, or both.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum: 
                  - xsize
                  - ysize
                  description: Size for the given axis.
                  example: xsize
                value:
                 type: string
                 example: "30"
                 description: Converted to type int.

  Process --> Crop:
    description: Crop an image by providing the top left and bottom right corners of the crop.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Crop
            example: Crop
          parameters:
            description: Must provide both (x,y) pairs.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - top_left_x
                  - top_left_y
                  - bottom_right_x
                  - bottom_right_y
                  description: Specify points.
                  example: top_left_x
                value:
                 type: string
                 description: Converted to type int.
                 example: "30"

  Process --> Mirror:
    description: Return a mirror image of the original image. Choose horizontal or verticle flip.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        properties:
          name:
            enum: 
            - Mirror
            example: Mirror
          parameters:
            description: Specify direction.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - flip
                  description: horizontal or vertical
                  example: horizontal
                value:
                 type: string
                 description: Converted to string.
                 enum:
                 - horizontal
                 - vertical
                 example: "horizontal"


  Process --> Color:
    description: Can be used to adjust the colour balance of an image, in a manner similar to the controls on a colour TV set. An enhancement factor of 0.0 gives a black and white image. A factor of 1.0 gives the original image.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Color
            example: Color
          parameters:
            description: Specify factor.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - factor
                  description: Any valid float value.
                  example: factor
                value:
                 type: string
                 description: Converted to type float.
                 example: "1.7"

  Process --> Brightness:
    description: Can be used to control the brightness of an image. An enhancement factor of 0.0 gives a black image. A factor of 1.0 gives the original image.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Brightness
            example: Brightness
          parameters:
            description: Specify factor.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - factor
                  description: Any valid float value.
                  example: factor
                value:
                 type: string
                 example: "1.7"
                 description: Converted to type float.

  Process --> Contrast:
    description: Can be used to control the contrast of an image, similar to the contrast control on a TV set. An enhancement factor of 0.0 gives a solid grey image. A factor of 1.0 gives the original image.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Contrast
            example: Contrast
          parameters:
            description: Specify factor.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - factor
                  description: Any valid float value.
                  example: factor
                value:
                 type: string
                 description: Converted to type float.
                 example: "1.7"

  Process --> Sharpen:
    description: Can be used to adjust the sharpness of an image. An enhancement factor of 0.0 gives a blurred image, a factor of 1.0 gives the original image, and a factor of 2.0 gives a sharpened image.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Sharpen
            example: Sharpen
          parameters:
            description: Specify factor.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - factor
                  description: Any valid float value.
                  example: factor
                value:
                 type: string
                 description: Converted to type float.
                 example: "1.7"

  Process --> Blur:
    description: Gaussian blur filter.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - Blur
            example: Blur
          parameters:
            description: Specify radius.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - radius
                  description: Radius value.
                  example: radius
                value:
                 type: string
                 description: Converted to type float.
                 example: "1.7"

  Process --> MaxFilter:
    description: Create a max filter. Picks the largest pixel value in a window with the given size.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - MaxFilter
            example: MaxFilter
          parameters:
            description: Specify size of filter window.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - size
                  description: Filter size value.
                  example: size
                value:
                 type: string
                 description: Converted to type int.
                 example: "3"

  Process --> MinFilter:
    description: Create a min filter. Picks the lowest pixel value in a window with the given size.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - MinFilter
            example: MinFilter
          parameters:
            description: Specify size of filter window.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - size
                  description: Filter size value.
                  example: size
                value:
                 type: string
                 description: Converted to type int.
                 example: "3"

  Process --> ModeFilter:
    description: Create a mode filter. Picks the mode pixel value in a window with the given size.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - ModeFilter
            example: ModeFilter
          parameters:
            description: Specify size of filter window.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - size
                  description: Filter size value.
                  example: size
                value:
                 type: string
                 description: Converted to type int.
                 example: "3"

  Process --> MedianFilter:
    description: Create a median filter. Picks the median pixel value in a window with the given size.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        required:
        - "parameters"
        properties:
          name:
            enum: 
            - MedianFilter
            example: MedianFilter
          parameters:
            description: Specify size of filter window.
            items:
              type: object
              properties:
                parameter:
                  type: string
                  enum:
                  - size
                  description: Filter size value.
                  example: size
                value:
                 type: string
                 description: Converted to type int.
                 example: "3"

  Process --> Edge:
    description: Enhance the edges on your image.
    allOf:
      - $ref: "#/definitions/Process"
      - type: object
        properties:
          name:
            enum: 
            - Edge
            example: Edge
